name: Deploy pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: 'pages'
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'

    - run: pnpm install hexo-cli -g
    - run: pnpm install --frozen-lockfile
    - run: hexo generate

    - uses: actions/upload-pages-artifact@v3
      with:
        path: public
    - id: deployment
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/deploy-pages@v4
